general:
  data_path: ../data/
  model_name: digit82/kobart-summarization
  output_dir: ./output/
inference:
  batch_size: 32
  ckt_path: model ckt path
  early_stopping: true
  generate_max_length: 100
  no_repeat_ngram_size: 2
  num_beams: 4
  remove_tokens:
  - <usr>
  - <s>
  - </s>
  - <pad>
  result_path: ./prediction/
tokenizer:
  bos_token: <s>
  decoder_max_len: 100
  encoder_max_len: 512
  eos_token: </s>
  special_tokens:
  - '#PersonName#'
  - '#Price#'
  - '#PhoneNumber#'
  - '#Address#'
  - '#DateOfBirth#'
  - '#PassportNumber#'
  - '#SSN#'
  - '#CardNumber#'
  - '#CarNumber#'
  - '#Email#'
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
  - '#Alex#'
  - '#Bob#'
  - '#Capital Airport#'
  - '#Kristin#'
  - '#Liliana#'
  - '#Mike Sanderson#'
  - '#Name#'
training:
  do_eval: true
  do_train: true
  early_stopping_patience: 3
  early_stopping_threshold: 0.001
  evaluation_strategy: epoch
  fp16: true
  generation_max_length: 100
  gradient_accumulation_steps: 1
  load_best_model_at_end: true
  logging_dir: ./logs
  logging_strategy: epoch
  lr_scheduler_type: cosine
  num_train_epochs: 20
  optim: adamw_torch
  overwrite_output_dir: true
  per_device_eval_batch_size: 32
  # learning_rate: 1.0e-05
  # per_device_train_batch_size: 50
  # warmup_ratio: 0.1
  # weight_decay: 0.01
  # --- ✨ 이 부분을 수정 ✨ -----------
  learning_rate: 5.94e-05                     
  per_device_train_batch_size: 50             
  weight_decay: 0.016
  warmup_ratio: 0.1
  use_aeda: false      # AEDA 데이터 증강을 사용할지 여부 (true/false)
  repetition: 1       # 원본 문장 1개당 생성할 증강 문장의 수
  use_bt: false      # Back Translation 데이터 증강을 사용할지 여부 (true/false)
  # -----------------------------------
  predict_with_generate: true
  report_to: wandb
  save_strategy: epoch
  save_total_limit: 5
  seed: 42
wandb:
  entity: brianmc75
  name: bart
  project: nlp_project
